# Generated by Django 4.2.5 on 2023-11-24 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0002_femalefeedback"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="gender",
        ),
        migrations.AlterField(
            model_name="user",
            name="is_male",
            field=models.BooleanField(default=True),
        ),
    ]
