# Generated by Django 4.2.5 on 2023-11-18 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0002_feedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="FemaleProduct",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "price",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=6),
                ),
                ("product_image", models.FileField(upload_to="products")),
            ],
        ),
    ]
