# Generated by Django 4.2.5 on 2023-11-18 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0003_femaleproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_male",
            field=models.BooleanField(default=False),
        ),
    ]
