# Generated by Django 4.2.5 on 2023-11-18 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0004_user_is_male"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")],
                default="male",
                max_length=10,
            ),
        ),
    ]
