# Generated by Django 4.2.5 on 2023-11-19 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0005_product_gender"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[("male", "Male"), ("female", "Female")], max_length=10
            ),
        ),
    ]
