# Generated by Django 4.2.5 on 2023-11-20 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0006_alter_product_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="booking_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
