# Generated by Django 4.2.5 on 2023-11-20 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0007_product_booking_time"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="booking_time",
        ),
    ]
