# Generated by Django 4.2.5 on 2023-11-21 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("GradNav", "0008_remove_product_booking_time"),
    ]

    operations = [
        migrations.CreateModel(
            name="FemaleBasketItem",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("quantity", models.IntegerField(default=1)),
                (
                    "basket_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="GradNav.basket"
                    ),
                ),
                (
                    "product_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="GradNav.femaleproduct",
                    ),
                ),
            ],
        ),
    ]
